/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc13x0_sdk_1_50_00_08\source\ti\blestack\blelib\host\host_pxxx.a"
"C:\ti\simplelink_cc13x0_sdk_1_50_00_08\source\ti\blestack\blelib\ctrl\cc1350\cc1350_ctrl_pxxx.a"
"C:\ti\simplelink_cc13x0_sdk_1_50_00_08\source\ti\blestack\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
